import type {
  GetStaticPaths,
  GetStaticProps,
  InferGetStaticPropsType,
  NextPage,
} from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import baseUrl from "../../baseUrl";

type Todo = {
  userId: number;
  id: number;
  title: string;
  completed: boolean;
};

type Props = {
  todo: Todo | undefined;
};

type QueryParams = {
  slug: string;
};

export const getStaticProps: GetStaticProps<Props, QueryParams> = async ({
  params,
}) => {
  const response = await fetch(`${baseUrl}/todos/${params?.slug ?? -1}`);
  const todo = (await response.json()) as Todo;

  console.log(todo);

  if (!todo?.id) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      todo,
    },
    revalidate: 10,
  };
};

export const getStaticPaths: GetStaticPaths<QueryParams> = async () => {
  const response = await fetch(`${baseUrl}/todos`);
  const todos = (await response.json()) as Todo[];

  const todosId = todos.slice(0, 3).map((todo: Todo) => ({
    params: {
      slug: todo.id.toString(),
    },
  }));

  return {
    paths: todosId,
    fallback: true, // fallback false returns 404 if path is not in the list
  };
};

const Post: NextPage<InferGetStaticPropsType<typeof getStaticProps>> = ({
  todo,
}) => {
  const router = useRouter();

  if (router.isFallback) {
    return <div>Loading...</div>;
  }

  if (!todo) {
    return <div>No Todos Found</div>;
  }

  return (
    <div>
      <Head>
        <title>{todo?.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <pre>
        {`// pre-rendered`}
        <br />
        {JSON.stringify(todo, null, 2)}
      </pre>
    </div>
  );
};

export default Post;
