import type {
  GetStaticPaths,
  GetStaticProps,
  InferGetStaticPropsType,
  NextPage,
} from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";

type Todo = {
  userId: number;
  id: number;
  title: string;
  completed: boolean;
};

type Props = {
  todo?: Todo;
};

type QueryParams = {
  slug: string;
};

export const getStaticProps: GetStaticProps<Props, QueryParams> = async ({
  params,
}) => {
  const data = await fetch(
    `https://jsonplaceholder.typicode.com/todos/${params?.slug ?? -1}`
  );
  const json = (await data.json()) as Todo;

  console.log(json);

  if (!json?.id) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      todo: json,
    },
  };
};

export const getStaticPaths: GetStaticPaths<QueryParams> = async () => {
  const request = await fetch("https://jsonplaceholder.typicode.com/todos");
  const json = (await request.json()) as Todo[];

  const todosId = json.slice(0, 3).map((todo: Todo) => ({
    params: {
      slug: todo.id.toString(),
    },
  }));

  return {
    paths: todosId,
    fallback: true, // fallback false returns 404 if path is not in the list
  };
};

const Post: NextPage<InferGetStaticPropsType<typeof getStaticProps>> = ({
  todo,
}) => {
  const router = useRouter();

  if (router.isFallback) {
    return <div>Loading...</div>;
  }

  return (
    <div>
      <Head>
        <title>{todo?.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <pre>
        {`// pre-rendered`}
        <br />
        {JSON.stringify(todo, null, 2)}
      </pre>
    </div>
  );
};

export default Post;
