import type {
  GetStaticPaths,
  GetStaticProps,
  InferGetStaticPropsType,
  NextPage,
} from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";

type Post = {
    userId: number;
    id: number;
    title: string;
    completed: boolean;
  };

type Props = {
  post: Post;
};

type QueryParams = {
  slug: string;
};

export const getStaticProps: GetStaticProps<Props, QueryParams> = async ({ params }) => {
  const data = await fetch(`https://jsonplaceholder.typicode.com/todos`);
  const json = await data.json();

  const post = json.find((post: Post) => post?.id.toString() === params?.slug);
  console.log({ sg: post });

  return {
    props: {
      post,
    },
  };
};

export const getStaticPaths: GetStaticPaths<QueryParams> = async () => {
  const request = await fetch("https://jsonplaceholder.typicode.com/todos");
  const json = (await request.json()) as Post[];

  const postsId = json.map((post: Post) => ({
    params: {
      slug: post.id.toString(),
    },
  }));

  return {
    paths: postsId,
    fallback: false,
  };
};

const Post: NextPage<InferGetStaticPropsType<typeof getStaticProps>> = ({
  post,
}) => {
  const router = useRouter();

  if (router.isFallback) {
    return <div>Loading...</div>;
  }

  return (
    <div>
      <Head>
        <title>{post?.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <pre>
        {`// pre-rendered`}
        <br />
        {JSON.stringify(post, null, 2)}
      </pre>
    </div>
  );
};

export default Post;
